#! /bin/sh

feh --bg-scale $HOME/n1/zzzz/summer.jpg
compton --config $HOME/.config/compton.conf -b
sxhkd &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
