#! /bin/sh

bspc monitor -d tty web play entertainment misc

bspc config border_width          2
bspc config window_gap            25
bspc config left_padding          25
bspc config right_padding         25

bspc config presel_feedback_color \#d75f5f
bspc config focused_border_color  \#d75f5f

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a firefox border=false

sxhkd &
$HOME/.config/polybar/launch.sh
